### ISSUE TITLE
Raster scan request does not close appointment page

### ISSUE THREAD

**Issue by Nolan-Hamilton** [YCPRadioTelescope/Radio-Tele-Frontend#44]
There is one UI issue remaining. When the user requests a Raster Scan appointment, it takes longer to copy over the two coordinates from the appointment page to the request appointment page. This requires the script to sleep for an extra second before resetting the form in the appointment page. This results in the appointment page not closing when the request is made, so the user has to click cancel after requesting the appointment in order to properly land back on the scheduler page. It does not cause an error, but it does ruin the user experience. Fix this!
![image](https://user-images.githubusercontent.com/36706225/77572226-fb6ae500-6ea4-11ea-871a-b2b6b1e5423e.png)
In the above image, the appointment screen in the background should close when the user opens the request screen.

**Comment by Antb41** [comment]
added setTimeout(() => {console.log("Waiting extra second for raster scan"); }, 1000); to allow for raster scan to finish processing
