### ISSUE TITLE
Celestial Body not set on Appointment Edit screen

### ISSUE THREAD

**Issue by Nolan-Hamilton** [YCPRadioTelescope/Radio-Tele-Frontend#49]
**The Celestial Body is not set in the drop down when opening the Appointment Edit screen**
When a user goes to edit a celestial body appointment, the celestial body input field is blank, which requires the user to set the celestial body. This ruins the user experience if the user is just trying to configure the SpectraCyber because the UPDATE button is disabled when the celestial body field is left empty.
![image.png](https://images.zenhubusercontent.com/5e345d68b64bc27d98017230/59018702-0c74-40b7-ba77-fdf35215bd85)
![image.png](https://images.zenhubusercontent.com/5e345d68b64bc27d98017230/a1ff8f40-d570-48c1-94d5-8557798df468)
When the user opens the Appointment Edit screen, all of the fields should be already filled with the current fields.

**Comment by Antb41** [comment]
To select a celestial body the name must be entered into the celestial body text box. Once a letter is typed a drop down list will popup with all possible celestial body choices containing that letter. Continuing to type the name will update the accuracy of the drop down options.

**Comment by Antb41** [comment]
celestial bodies must be entered in the celestial body tab under the admin menu to be accessible in the drop down menu
