### ISSUE TITLE
Admin approval of profile pictures

### ISSUE THREAD

**Issue by dhilbert1** [YCPRadioTelescope/Radio-Tele-Frontend#76]

**Comment by quintanamo** [comment]
I will be working on a section that appears in the profile page exclusively for admins that opens a page/modal to accept users' profile picture submissions.

**Comment by quintanamo** [comment]
I have been encountering several different errors when trying to start making the section that allows admins to approve profile pictures.  I am still in the process of diagnosing where it is an issue in the code or in my setup.

**Comment by quintanamo** [comment]
A button was added within manage users that allows an admin to view a modal which allows them to see a user's profile picture while also giving them option to approve or deny it.
