### ISSUE TITLE
ApiDriver routes pulling tokens for non protected routes

### ISSUE THREAD

**Issue by lgartrell** [YCPRadioTelescope/Radio-Tele-Frontend#85]
We found this bug when trying to register a new account, but the register route was pulling an expired JWT token from the browser's cache.

## How to reproduce
* Register an account 
* Log in with that account
* Let the token expire (manually change system time, or wait long enough)
* Try to register a new account, get the JWT expired token exception on the backend

## Work Left
* Verify there are no more routes that are pulling JWT tokens that do not need a token

**Comment by Antb41** [comment]
I went through and verified that the rest of the routes are not pulling JWT tokens. Only when trying to register a new account reproduces the issue but this has been fixed anyway.

**Comment by Antb41** [comment]
updated ApiDriver routes so JWT tokens are only being pulled when needed
